name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer pytest
        run: pip install pytest

      - name: Lancer les tests
        run: pytest test_app.py

  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Se connecter à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build et Push l'image Docker
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/monapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Déployer sur le VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_IP }}
          username: joelt
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/monapp:latest
            docker stop monapp || true
            docker rm monapp || true
            docker run -d --name monapp ${{ secrets.DOCKER_USERNAME }}/monapp:latest